version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - e2e

linters:
  default: all
  disable:
    - depguard
    - wsl
    - nolintlint

  settings:
    varnamelen:
      ignore-names:
        - db
        - w
        - r
        - m
    exhaustruct:
      include:
        - 'github\.com/6ermvH/url-shortener\.'

  exclusions:
    generated: strict
    warn-unused: false
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - noinlineerr
          - errchkjson
      - path: ^cmd/
        linters:
          - revive

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: strict
